#!/usr/bin/env node
var program = require( 'commander' );
var birth = require( './' );

program
	.version( require( './package.json' ).version );

program
	.command( 'init' )
	.description( '(re)set inilial settings' )
	.action( birth.init );

program
	.command( 'generate <name>' )
	.alias( 'gen' )
	.description( 'generate named boilerplate' )
	.option( '-p, --path <path>', 'where to generate boilerplate' )
	.action( birth.generate );

program
	.command( 'list' )
	.description( 'list available boilerplates' )
	.action( birth.list );

program
	.command( 'regist <path>' )
	.description( 'regist new boilerplate from path' )
	.action( birth.regist );

program.parse( process.argv );

if ( program.args.length === 0 ) {
	program.help();
	process.exit();
}
